services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    build:
      context: .
      dockerfile: Bookify.Api/Dockerfile
    depends_on:
      - bookify-db
  
  bookify-db:
    image: postgres:17.5

  bookify-idp:
    image: quay.io/keycloak/keycloak:26.2

volumes:
  postgres_bookify:

